package main

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

func fmtN(v float64) string {
	a := v
	if a < 0 {
		a = -a
	}
	switch {
	case a >= 1000:
		return addCommas(strconv.FormatFloat(v, 'f', 0, 64))
	case a >= 10:
		return strconv.FormatFloat(v, 'f', 0, 64)
	default:
		return strconv.FormatFloat(v, 'f', 1, 64)
	}
}

func addCommas(s string) string {
	neg := strings.HasPrefix(s, "-")
	s = strings.TrimPrefix(s, "-")
	var out []byte
	for i, c := range []byte(s) {
		if i > 0 && (len(s)-i)%3 == 0 {
			out = append(out, ',')
		}
		out = append(out, c)
	}
	if neg {
		return "-" + string(out)
	}
	return string(out)
}

func perOp(total int64, ops int) string {
	if ops == 0 {
		return ""
	}
	return fmtN(float64(total) / float64(ops))
}

type view struct {
	f    *File
	rows map[string]Row
}

func newView(f *File) view {
	return view{f: f, rows: f.Rows}
}

func (v view) get(structure, value, mode, workload string, n int) (Row, bool) {
	k := Row{Structure: structure, Value: value, Mode: mode, Workload: workload, N: n}.Key()
	r, ok := v.rows[k]
	if !ok || r.Skip != "" || r.Err != "" {
		return r, false
	}
	return r, true
}

func (v view) sizes() []int {
	seen := map[int]bool{}
	for _, r := range v.rows {
		seen[r.N] = true
	}
	var out []int
	for n := range seen {
		out = append(out, n)
	}
	sort.Ints(out)
	return out
}

// Markdown is the generated report. Everything in it comes from the result
// files: nothing is typed by hand, so nothing can drift from the data.
func Markdown(s *Suite, files []*File) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n%s\n\n", s.Title, s.Blurb)
	b.WriteString("> Generated by `gnobench report`. Do not edit: every number below is read out of\n")
	b.WriteString("> `results/" + s.Name + "/*.json`, which `gnobench run` writes.\n\n")

	b.WriteString("## What produced these numbers\n\n")
	b.WriteString("| machine | hardware | go | gno revision | gnobench | rows | updated |\n|---|---|---|---|---|--:|---|\n")
	for _, f := range files {
		tool := f.Env.ToolVer
		if tool == "" {
			tool = "unknown"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | `%s` | `%s` | %d | %s |\n",
			f.Env.ID, f.Env.Short(), f.Env.GoVer, f.Env.GnoShort(), tool, len(f.Rows), f.UpdatedAt)
	}
	b.WriteString("\n")

	for _, f := range files {
		w := f.Warn(30)
		var lines []string
		if len(w.MixedGno) > 1 {
			lines = append(lines, "**Rows in `"+f.Env.ID+"` were measured against more than one gno revision**: "+
				strings.Join(w.MixedGno, ", ")+". They are not strictly comparable; re-run the suite to settle it.")
		}
		if len(w.Stale) > 0 {
			lines = append(lines, fmt.Sprintf("%d row(s) in `%s` are over 30 days old (oldest %d days).",
				len(w.Stale), f.Env.ID, w.OldestDays))
		}
		if len(w.Unstable) > 0 {
			lines = append(lines, fmt.Sprintf("**%d row(s) in `%s` did not reproduce across repeats**: %s",
				len(w.Unstable), f.Env.ID, strings.Join(trim(w.Unstable, 5), ", ")))
		}
		if len(w.Failed) > 0 {
			lines = append(lines, fmt.Sprintf("**%d row(s) in `%s` failed**: %s",
				len(w.Failed), f.Env.ID, strings.Join(trim(w.Failed, 5), "; ")))
		}
		for _, l := range lines {
			b.WriteString("> [!WARNING]\n> " + l + "\n\n")
		}
	}

	if s.HowToRead != "" {
		b.WriteString("## How to read this\n\n" + s.HowToRead + "\n")
	} else {
		b.WriteString(`## How to read this

| axis | where it comes from | how far to trust it |
|---|---|---|
| **gas** | the VM's meter: CPU cycles, allocations, store reads and writes, in one figure | comparable between rows, **not** mainnet gas (the filetest meter is infinite and the test gas config is not the chain's) |
| **bytes** | ` + "`Store.RealmStorageDiffs()`" + `, the net byte delta of persisted realm objects | real: at ` + "`storage_price`" + ` 100 ugnot/byte this **is** the deposit |
| **wall** | timed around the call | carries a fixed per-run type-check cost, so only large deltas mean anything |

Every workload subtracts a baseline whose body is an exact prefix of its own, so each figure
is the measured phase alone.

**warm** means the container was built and measured inside one run, so every object it touches
is already live in the VM's per-transaction object cache. **cold** means it was built during
package initialisation, which the filetest runner commits before ` + "`main`" + ` runs, so the measured
phase deserialises every object it touches. A deployed realm is always cold.

`)
	}

	for _, f := range files {
		v := newView(f)
		if len(files) > 1 {
			fmt.Fprintf(&b, "# Machine `%s`\n\n", f.Env.ID)
		}
		b.WriteString(wiringSection(s, v))
		b.WriteString(winnersSection(s, v))
		b.WriteString(txSection(s, v))
		b.WriteString(warmColdSection(s, v))
		b.WriteString(storageSection(s, v))
		b.WriteString(pivotSection(s, v))
		b.WriteString(rawSection(s, v))
	}
	return b.String()
}

func trim(ss []string, k int) []string {
	if len(ss) <= k {
		return ss
	}
	return append(ss[:k:k], "...")
}

// wiringSection is the whole point of the wiring suite: the same writes, the
// same final state, the same deposit, and a write volume that differs by two
// orders of magnitude depending only on how many transactions they arrived in.
func wiringSection(s *Suite, v view) string {
	if s.Name != "wiring" {
		return ""
	}
	var b strings.Builder
	b.WriteString("## Batched against one at a time\n\n")
	b.WriteString("Both columns perform the same writes and end at the same state, so the **deposit is\n")
	b.WriteString("identical**. `kv bytes` is what the key/value store was actually asked to write, which\n")
	b.WriteString("is what the node's disk absorbs and what no meter here charges for.\n\n")
	for _, n := range v.sizes() {
		type row struct {
			name            string
			deposit         int64
			oneKV, manyKV   int64
			oneGas, manyGas int64
			amp             float64
		}
		var rows []row
		for _, c := range wiringCandidates {
			one, ok1 := v.get(c.Name, "str", "cold", shapeOneTx, n)
			many, ok2 := v.get(c.Name, "str", "cold", shapePerTx, n)
			if !ok1 || !ok2 || one.KVSetBytes == 0 {
				continue
			}
			rows = append(rows, row{
				name: c.Name, deposit: one.Bytes,
				oneKV: one.KVSetBytes, manyKV: many.KVSetBytes,
				oneGas: one.Gas, manyGas: many.Gas,
				amp: float64(many.KVSetBytes) / float64(one.KVSetBytes),
			})
		}
		if len(rows) == 0 {
			continue
		}
		sort.Slice(rows, func(i, j int) bool { return rows[i].manyKV < rows[j].manyKV })
		fmt.Fprintf(&b, "### %s writes\n\n", addCommas(strconv.Itoa(n)))
		b.WriteString("| candidate | deposit (both) | kv bytes, 1 tx | kv bytes, one tx each | amplification | gas, one tx each |\n")
		b.WriteString("|---|--:|--:|--:|--:|--:|\n")
		for _, r := range rows {
			fmt.Fprintf(&b, "| `%s` | %s | %s | **%s** | %.1fx | %s |\n",
				r.name, addCommas(strconv.FormatInt(r.deposit, 10)),
				addCommas(strconv.FormatInt(r.oneKV, 10)),
				addCommas(strconv.FormatInt(r.manyKV, 10)),
				r.amp, addCommas(strconv.FormatInt(r.manyGas, 10)))
		}
		b.WriteString("\n")
	}
	return b.String()
}

// winnersSection is the answer, computed rather than written: for each size
// and each single-operation transaction, which candidate is cheapest. Where the
// winner changes between two sizes, that is a crossover, and it is called out,
// because "use X" is only ever true up to some n.
func winnersSection(s *Suite, v view) string {
	var ops []Workload
	for _, w := range s.Workloads {
		if w.Light && w.Baseline != "" {
			ops = append(ops, w)
		}
	}
	if len(ops) == 0 {
		return ""
	}
	sizes := v.sizes()
	var b strings.Builder
	b.WriteString("## Cheapest per size\n\n")
	b.WriteString("One transaction, one operation, cold, string values. A candidate that wins at one\n")
	b.WriteString("size and loses at the next is a crossover, and the note says so.\n\n")
	for _, group := range s.Groups() {
		rows := 0
		var body strings.Builder
		for _, w := range ops {
			if w.Group != group {
				continue
			}
			var cells []string
			prev := ""
			cross := ""
			for _, n := range sizes {
				best, bestV := "", 0.0
				for _, st := range s.Structures {
					if st.Group != group || !st.takesValue("str") {
						continue
					}
					r, ok := v.get(st.Name, "str", w.mode(), w.Name, n)
					if !ok || r.Ops == 0 {
						continue
					}
					val := float64(r.DGas) / float64(r.Ops)
					if best == "" || val < bestV {
						best, bestV = st.Name, val
					}
				}
				if best == "" {
					cells = append(cells, "")
					continue
				}
				cells = append(cells, fmt.Sprintf("`%s` (%s)", best, fmtN(bestV)))
				if prev != "" && prev != best && cross == "" {
					cross = fmt.Sprintf("changes hands before n = %s", addCommas(strconv.Itoa(n)))
				}
				prev = best
			}
			rows++
			fmt.Fprintf(&body, "| %s | %s | %s |\n", w.Name, strings.Join(cells, " | "), cross)
		}
		if rows == 0 {
			continue
		}
		fmt.Fprintf(&b, "### %s\n\n| operation |", group)
		for _, n := range sizes {
			fmt.Fprintf(&b, " n = %s |", addCommas(strconv.Itoa(n)))
		}
		b.WriteString(" |\n|---|")
		for range sizes {
			b.WriteString("---|")
		}
		b.WriteString("---|\n")
		b.WriteString(body.String())
		b.WriteString("\n")
	}
	return b.String()
}

// txSection is the headline: what ONE operation costs in ONE transaction
// against a container of a given size, with nothing cached. It is the only
// table here that maps directly onto a realm's real per-call cost.
func txSection(s *Suite, v view) string {
	var b strings.Builder
	var any bool
	for _, w := range s.Workloads {
		if w.Light && w.Baseline != "" {
			any = true
		}
	}
	if !any {
		return ""
	}
	b.WriteString("## One transaction, one operation\n\n")
	b.WriteString("Cold. The container was committed by an earlier transaction and this one touches it\n")
	b.WriteString("once. **This is the number a realm pays per call**, and it is the one a warm benchmark\n")
	b.WriteString("hides: a container held in a single persisted object has to be deserialised whole on\nfirst touch.\n\n")

	for _, group := range s.Groups() {
		var ops []Workload
		for _, w := range s.Workloads {
			if w.Group == group && w.Light && w.Baseline != "" {
				ops = append(ops, w)
			}
		}
		if len(ops) == 0 {
			continue
		}
		for _, n := range v.sizes() {
			rows := txRows(s, v, group, "str", n, ops)
			if len(rows) == 0 {
				continue
			}
			fmt.Fprintf(&b, "### %s, n = %s, string values\n\n| candidate |", group, addCommas(strconv.Itoa(n)))
			for _, w := range ops {
				fmt.Fprintf(&b, " %s |", w.Name)
			}
			b.WriteString("\n|---|")
			for range ops {
				b.WriteString("--:|")
			}
			b.WriteString("\n")
			for _, r := range rows {
				fmt.Fprintf(&b, "| `%s` |", r.name)
				for _, c := range r.cells {
					fmt.Fprintf(&b, " %s |", c)
				}
				b.WriteString("\n")
			}
			b.WriteString("\n")
		}
	}
	return b.String()
}

type namedRow struct {
	name  string
	sort  float64
	cells []string
}

func txRows(s *Suite, v view, group, value string, n int, ops []Workload) []namedRow {
	var out []namedRow
	for _, st := range s.Structures {
		if st.Group != group || !st.takesValue(value) {
			continue
		}
		nr := namedRow{name: st.Name, sort: 1 << 60}
		any := false
		for _, w := range ops {
			r, ok := v.get(st.Name, value, w.mode(), w.Name, n)
			if !ok {
				nr.cells = append(nr.cells, "n/a")
				continue
			}
			any = true
			nr.cells = append(nr.cells, fmtN(float64(r.DGas)/float64(max(r.Ops, 1))))
			if w.Name == "tx_read" || w.Name == "tx_at" {
				nr.sort = float64(r.DGas)
			}
		}
		if any {
			out = append(out, nr)
		}
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].sort < out[j].sort })
	return out
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}

// warmColdSection is the correction: the same operation measured both ways.
func warmColdSection(s *Suite, v view) string {
	var b strings.Builder
	var head bool
	for _, n := range v.sizes() {
		var rows []namedRow
		for _, st := range s.Structures {
			if st.Group != "kv" {
				continue
			}
			wr, ok1 := v.get(st.Name, "str", "warm", "get_hit", n)
			cr, ok2 := v.get(st.Name, "str", "cold", "cold_get_all", n)
			if !ok1 || !ok2 || wr.Ops == 0 {
				continue
			}
			warm := float64(wr.DGas) / float64(wr.Ops)
			cold := float64(cr.DGas) / float64(cr.Ops)
			ratio := 0.0
			if warm > 0 {
				ratio = cold / warm
			}
			rows = append(rows, namedRow{
				name: st.Name, sort: cold,
				cells: []string{fmtN(warm), fmtN(cold), strconv.FormatFloat(ratio, 'f', 2, 64) + "x"},
			})
		}
		if len(rows) == 0 {
			continue
		}
		if !head {
			head = true
			b.WriteString("## Warm against cold\n\n")
			b.WriteString("Gas per read, all n reads. Warm reads sit in the VM's object cache; cold reads start\n")
			b.WriteString("from a committed store. The ratio is how much a warm benchmark flatters a container.\n\n")
		}
		sort.SliceStable(rows, func(i, j int) bool { return rows[i].sort < rows[j].sort })
		fmt.Fprintf(&b, "### n = %s\n\n| candidate | warm gas/read | cold gas/read | cold / warm |\n|---|--:|--:|--:|\n", addCommas(strconv.Itoa(n)))
		for _, r := range rows {
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", r.name, r.cells[0], r.cells[1], r.cells[2])
		}
		b.WriteString("\n")
	}
	return b.String()
}

func storageSection(s *Suite, v view) string {
	var b strings.Builder
	head := false
	for _, value := range []string{"str", "obj"} {
		for _, n := range v.sizes() {
			var rows []namedRow
			for _, st := range s.Structures {
				if !st.takesValue(value) {
					continue
				}
				wl := "insert_rand"
				if st.Group == "list" {
					wl = "append_n"
				}
				r, ok := v.get(st.Name, value, "warm", wl, n)
				if !ok || r.Ops == 0 {
					continue
				}
				per := float64(r.DBytes) / float64(r.Ops)
				rows = append(rows, namedRow{
					name: st.Name, sort: per,
					cells: []string{fmtN(per), fmtN(per*100000*100/1e6) + " GNOT"},
				})
			}
			if len(rows) == 0 {
				continue
			}
			if !head {
				head = true
				b.WriteString("## Storage per entry\n\nBytes of realm state each entry costs, and the deposit that locks at 100 ugnot/byte.\n\n")
			}
			sort.SliceStable(rows, func(i, j int) bool { return rows[i].sort < rows[j].sort })
			fmt.Fprintf(&b, "### n = %s, %s values\n\n| candidate | B/entry | deposit for 100k entries |\n|---|--:|--:|\n",
				addCommas(strconv.Itoa(n)), valueLabel(value))
			for _, r := range rows {
				fmt.Fprintf(&b, "| `%s` | %s | %s |\n", r.name, r.cells[0], r.cells[1])
			}
			b.WriteString("\n")
		}
	}
	return b.String()
}

func valueLabel(v string) string {
	if v == "obj" {
		return "live object"
	}
	return "string"
}

// pivotSection is the reading view: candidates down the side, workloads across.
func pivotSection(s *Suite, v view) string {
	var b strings.Builder
	b.WriteString("## Every workload\n\n")
	for _, group := range s.Groups() {
		for _, mode := range []string{"warm", "cold"} {
			var wls []Workload
			for _, w := range s.Workloads {
				if w.Group == group && w.mode() == mode && !w.Light {
					wls = append(wls, w)
				}
			}
			if len(wls) == 0 {
				continue
			}
			for _, value := range []string{"str", "obj"} {
				for _, n := range v.sizes() {
					tbl := pivotTable(s, v, group, mode, value, n, wls)
					if tbl == "" {
						continue
					}
					fmt.Fprintf(&b, "### %s, %s, gas per op, n = %s, %s values\n\n",
						group, mode, addCommas(strconv.Itoa(n)), valueLabel(value))
					b.WriteString(tbl)
				}
			}
		}
	}
	return b.String()
}

func pivotTable(s *Suite, v view, group, mode, value string, n int, wls []Workload) string {
	var body strings.Builder
	rows := 0
	for _, st := range s.Structures {
		if st.Group != group || !st.takesValue(value) {
			continue
		}
		var cells []string
		any := false
		for _, w := range wls {
			r, ok := v.get(st.Name, value, mode, w.Name, n)
			switch {
			case ok:
				any = true
				cells = append(cells, perOp(r.DGas, r.Ops))
			default:
				k := Row{Structure: st.Name, Value: value, Mode: mode, Workload: w.Name, N: n}.Key()
				if rr, present := v.rows[k]; present && rr.Skip != "" {
					cells = append(cells, "n/a")
				} else if present && rr.Err != "" {
					cells = append(cells, "ERR")
				} else {
					cells = append(cells, "")
				}
			}
		}
		if !any {
			continue
		}
		rows++
		fmt.Fprintf(&body, "| `%s` | %s |\n", st.Name, strings.Join(cells, " | "))
	}
	if rows == 0 {
		return ""
	}
	var head strings.Builder
	head.WriteString("| candidate |")
	for _, w := range wls {
		fmt.Fprintf(&head, " %s |", w.Name)
	}
	head.WriteString("\n|---|")
	for range wls {
		head.WriteString("--:|")
	}
	head.WriteString("\n")
	return head.String() + body.String() + "\n"
}

// rawSection prints every row. A report that only shows derived figures asks
// the reader to trust the derivation.
func rawSection(s *Suite, v view) string {
	var b strings.Builder
	b.WriteString("## Raw results\n\n")
	fmt.Fprintf(&b, "%d rows, every one of them. `d_*` columns are baseline-subtracted.\n\n", len(v.rows))
	b.WriteString("<details><summary>Expand</summary>\n\n")
	b.WriteString("| candidate | value | mode | workload | n | ops | gas | bytes | d_gas | d_bytes | wall ms | measured | note |\n")
	b.WriteString("|---|---|---|---|--:|--:|--:|--:|--:|--:|--:|---|---|\n")
	keys := make([]string, 0, len(v.rows))
	for k := range v.rows {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		r := v.rows[k]
		note := r.Skip
		if r.Err != "" {
			note = "FAILED: " + r.Err
		} else if r.Skip == "" && !r.Stable {
			note = "unstable across repeats"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %d | %d | %d | %d | %d | %d | %s | %s | %s |\n",
			r.Structure, r.Value, r.Mode, r.Workload, r.N, r.Ops, r.Gas, r.Bytes, r.DGas, r.DBytes,
			strconv.FormatFloat(float64(r.DWallNs)/1e6, 'f', 1, 64), shortDate(r.MeasuredAt), note)
	}
	b.WriteString("\n</details>\n\n")
	return b.String()
}

func shortDate(s string) string {
	if len(s) >= 10 {
		return s[:10]
	}
	return s
}
