// xmathgen writes p/moul/xmath: Max, Min, Clamp, Abs and Sign for every
// built-in numeric type, one concrete function per type.
//
// gno has no generics, so the alternative to generating these is writing the
// same three-line helper again in every realm. The package has carried a
// "Code generated by generator.go; DO NOT EDIT." header since it was imported,
// but no generator was ever committed: the header was a claim nobody could act
// on, and editing the files by hand meant editing something that says not to.
// This is that generator, reconstructed from the output it describes. Running
// it reproduces the committed files byte for byte, which is what `-check`
// verifies.
//
// Unsigned types get no Abs or Sign: both are trivially themselves and 1, and
// offering them would only invite an overflow bug at the call site.
//
// Usage:
//
//	go -C tools run ./xmathgen            # rewrite the two files in place
//	go -C tools run ./xmathgen -check     # fail if they are stale (CI)
//	go -C tools run ./xmathgen -o DIR     # write somewhere else
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// numType is one row of the table this generator expands.
type numType struct {
	Name string // exported suffix: "Int8", "Uint", "Float64"
	Go   string // the gno type: "int8", "uint", "float64"
	// Signed reports whether Abs and Sign are emitted. Unsigned types get
	// neither; see the package doc.
	Signed bool
	// Zero is the literal used for the Sign(0) test case. Floats use 0.0 so
	// the case reads as a float, matching the rest of the block.
	Zero string
}

var types = []numType{
	{"Int8", "int8", true, "0"},
	{"Int16", "int16", true, "0"},
	{"Int32", "int32", true, "0"},
	{"Int64", "int64", true, "0"},
	{"Int", "int", true, "0"},
	{"Uint8", "uint8", false, ""},
	{"Uint16", "uint16", false, ""},
	{"Uint32", "uint32", false, ""},
	{"Uint64", "uint64", false, ""},
	{"Uint", "uint", false, ""},
	{"Float32", "float32", true, "0.0"},
	{"Float64", "float64", true, "0.0"},
}

const header = "// Code generated by generator.go; DO NOT EDIT.\n"

func genSource() string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("package xmath\n")
	for _, t := range types {
		fmt.Fprintf(&b, "\n// %s helpers\n", t.Name)
		// No blank line between the type comment and its first function; every
		// later function in the block is preceded by one.
		fmt.Fprintf(&b, "func Max%s(a, b %s) %s {\n\tif a > b {\n\t\treturn a\n\t}\n\treturn b\n}\n", t.Name, t.Go, t.Go)
		fmt.Fprintf(&b, "\nfunc Min%s(a, b %s) %s {\n\tif a < b {\n\t\treturn a\n\t}\n\treturn b\n}\n", t.Name, t.Go, t.Go)
		fmt.Fprintf(&b, "\nfunc Clamp%s(value, min, max %s) %s {\n\tif value < min {\n\t\treturn min\n\t}\n\tif value > max {\n\t\treturn max\n\t}\n\treturn value\n}\n", t.Name, t.Go, t.Go)
		if !t.Signed {
			continue
		}
		fmt.Fprintf(&b, "\nfunc Abs%s(x %s) %s {\n\tif x < 0 {\n\t\treturn -x\n\t}\n\treturn x\n}\n", t.Name, t.Go, t.Go)
		fmt.Fprintf(&b, "\nfunc Sign%s(x %s) %s {\n\tif x < 0 {\n\t\treturn -1\n\t}\n\tif x > 0 {\n\t\treturn 1\n\t}\n\treturn 0\n}\n", t.Name, t.Go, t.Go)
	}
	return b.String()
}

// check emits one `if <expr> != <want>` assertion with the matching t.Error.

func genTest() string {
	var b strings.Builder
	b.WriteString("package xmath\n\nimport \"testing\"\n")
	for _, t := range types {
		fmt.Fprintf(&b, "\nfunc Test%sHelpers(t *testing.T) {\n", t.Name)

		fmt.Fprintf(&b, "\t// Test Max%s\n", t.Name)
		assert(&b, fmt.Sprintf("Max%s(1, 2)", t.Name), "2")
		if t.Signed {
			assert(&b, fmt.Sprintf("Max%s(-1, -2)", t.Name), "-1")
		}

		fmt.Fprintf(&b, "\n\t// Test Min%s\n", t.Name)
		assert(&b, fmt.Sprintf("Min%s(1, 2)", t.Name), "1")
		if t.Signed {
			assert(&b, fmt.Sprintf("Min%s(-1, -2)", t.Name), "-2")
		}

		fmt.Fprintf(&b, "\n\t// Test Clamp%s\n", t.Name)
		assert(&b, fmt.Sprintf("Clamp%s(5, 1, 3)", t.Name), "3")
		assert(&b, fmt.Sprintf("Clamp%s(0, 1, 3)", t.Name), "1")
		assert(&b, fmt.Sprintf("Clamp%s(2, 1, 3)", t.Name), "2")

		if t.Signed {
			fmt.Fprintf(&b, "\n\t// Test Abs%s\n", t.Name)
			assert(&b, fmt.Sprintf("Abs%s(-5)", t.Name), "5")
			assert(&b, fmt.Sprintf("Abs%s(5)", t.Name), "5")

			fmt.Fprintf(&b, "\n\t// Test Sign%s\n", t.Name)
			assert(&b, fmt.Sprintf("Sign%s(-5)", t.Name), "-1")
			assert(&b, fmt.Sprintf("Sign%s(5)", t.Name), "1")
			assert(&b, fmt.Sprintf("Sign%s(%s)", t.Name, t.Zero), "0")
		}

		b.WriteString("\n}\n")
	}
	return b.String()
}

func assert(b *strings.Builder, expr, want string) {
	fmt.Fprintf(b, "\tif %s != %s {\n\t\tt.Error(\"%s should be %s\")\n\t}\n", expr, want, expr, want)
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "xmathgen:", err)
		os.Exit(1)
	}
}

func run() error {
	out := flag.String("o", "../p/moul/xmath", "directory to write into")
	checkOnly := flag.Bool("check", false, "fail if the committed files are stale instead of rewriting them")
	flag.Parse()

	files := map[string]string{
		"xmath.gen.gno":      genSource(),
		"xmath.gen_test.gno": genTest(),
	}

	var stale []string
	for name, want := range files {
		p := filepath.Join(*out, name)
		if *checkOnly {
			got, err := os.ReadFile(p)
			if err != nil {
				return err
			}
			if string(got) != want {
				stale = append(stale, p)
			}
			continue
		}
		if err := os.WriteFile(p, []byte(want), 0o644); err != nil {
			return err
		}
	}

	if *checkOnly {
		if len(stale) > 0 {
			return fmt.Errorf("stale, re-run `go -C tools run ./xmathgen`: %s", strings.Join(stale, " "))
		}
		fmt.Println("xmathgen: p/moul/xmath is up to date")
		return nil
	}
	fmt.Printf("xmathgen: wrote %d file(s) into %s\n", len(files), *out)
	return nil
}
