package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Managed footer markers in every per-package README.md. Content ABOVE the
// begin marker is hand-authored (package docs); the block between the markers is
// generated (repo link + disclaimer) and must not be hand-edited.
const (
	pkgFooterBegin = "<!-- BEGIN GNOCONTRACTS FOOTER (generated by `make readmes`; do not edit below) -->"
	pkgFooterEnd   = "<!-- END GNOCONTRACTS FOOTER -->"
	repoURL        = "https://github.com/moul/gno-contracts"
	disclaimerURL  = "https://github.com/moul/gno-contracts/blob/main/DISCLAIMER.md"
)

// cmdReadmes ensures every contract directory has a README.md that (a) describes
// the package, (b) links back to the repo, and (c) carries the standard
// disclaimer — the stronger "experimental / vibe-coded" variant for packages
// under an /x/ path. Hand-written content above the footer marker is preserved;
// a stub is created for packages that have no README yet.
func cmdReadmes(root string) error {
	m, err := loadManifest(root)
	if err != nil {
		return err
	}
	created, updated := 0, 0
	for _, c := range m.Contracts {
		p := filepath.Join(root, filepath.FromSlash(c.Dir), "README.md")
		footer := pkgFooter(c)

		b, err := os.ReadFile(p)
		if os.IsNotExist(err) {
			if err := os.WriteFile(p, []byte(pkgStub(c)+"\n"+footer+"\n"), 0o644); err != nil {
				return err
			}
			created++
			continue
		} else if err != nil {
			return err
		}

		content := string(b)
		var next string
		i := strings.Index(content, pkgFooterBegin)
		j := strings.Index(content, pkgFooterEnd)
		if i >= 0 && j > i {
			next = strings.TrimRight(content[:i], "\n") + "\n\n" + footer + content[j+len(pkgFooterEnd):]
		} else {
			// no managed block yet: append one, preserving existing content
			next = strings.TrimRight(content, "\n") + "\n\n" + footer + "\n"
		}
		if next != content {
			if err := os.WriteFile(p, []byte(next), 0o644); err != nil {
				return err
			}
			updated++
		}
	}
	fmt.Printf("readmes: %d created, %d updated (%d contracts)\n", created, updated, len(m.Contracts))
	return nil
}

// isExperimental reports whether a contract lives under an /x/ path segment.
func isExperimental(dir string) bool {
	for _, seg := range strings.Split(dir, "/") {
		if seg == "x" {
			return true
		}
	}
	return false
}

func pkgStub(c Contract) string {
	desc := c.Description
	if desc == "" {
		desc = "_TODO: describe this package._"
	}
	return "# `" + c.PkgPath + "`\n\n" + desc + "\n"
}

func pkgFooter(c Contract) string {
	var b strings.Builder
	b.WriteString(pkgFooterBegin)
	b.WriteString("\n\n---\n\n")
	b.WriteString("Part of **[moul/gno-contracts](" + repoURL + ")** — moul's versioned " +
		"gno.land contracts. See the repository for the full catalog, build/test " +
		"tooling, and usage.\n\n")
	if c.Source != "" {
		src := c.Source
		if strings.HasPrefix(src, "http") {
			src = "[" + src + "](" + src + ")"
		}
		b.WriteString("Provenance: imported — see " + src + " for context and metadata.\n\n")
	}
	if c.Ignored {
		b.WriteString("> 💤 **Archived version.** This package does not build on current " +
			"gno master and is marked `ignore = true` (skipped by the toolchain and CI). " +
			"It is kept for reference; use the latest ported version of this package instead.\n\n")
	}
	if isExperimental(c.Dir) {
		b.WriteString("> 🧪 **Highly experimental — potentially vibe-coded.** Not audited; " +
			"may break, change, or be removed at any time. Do not use with anything of " +
			"value. Full disclaimer: [DISCLAIMER](" + disclaimerURL + ").\n")
	} else {
		b.WriteString("> ⚠️ **Disclaimer:** provided as-is, without warranty; not " +
			"security-audited. Full disclaimer: [DISCLAIMER](" + disclaimerURL + ").\n")
	}
	b.WriteString("\n")
	b.WriteString(pkgFooterEnd)
	return b.String()
}
