package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	tableBegin = "<!-- BEGIN CONTRACTS TABLE (generated by `make readme`; do not edit by hand) -->"
	tableEnd   = "<!-- END CONTRACTS TABLE -->"
)

// cmdReadme regenerates the contracts table in README.md between the marker
// comments, from contracts.json.
func cmdReadme(root string) error {
	m, err := loadManifest(root)
	if err != nil {
		return err
	}
	readmePath := filepath.Join(root, "README.md")
	b, err := os.ReadFile(readmePath)
	if err != nil {
		return err
	}
	content := string(b)
	i := strings.Index(content, tableBegin)
	j := strings.Index(content, tableEnd)
	if i < 0 || j < 0 || j < i {
		return fmt.Errorf("README.md missing the contracts-table markers")
	}
	var out strings.Builder
	out.WriteString(content[:i])
	out.WriteString(tableBegin)
	out.WriteString("\n\n")
	out.WriteString(renderTable(m))
	out.WriteString("\n")
	out.WriteString(content[j:])
	return os.WriteFile(readmePath, []byte(out.String()), 0o644)
}

func renderTable(m *Manifest) string {
	if len(m.Contracts) == 0 {
		return "_No contracts yet._\n"
	}
	var b strings.Builder
	// header: Package, then one column per network, then Monorepo + Deps.
	b.WriteString("| Package |")
	for _, n := range m.Networks {
		b.WriteString(" " + n.Name + " |")
	}
	b.WriteString(" Monorepo | Deps |\n|---|")
	for range m.Networks {
		b.WriteString("---|")
	}
	b.WriteString("---|---|\n")
	// rows
	for _, c := range m.Contracts {
		// Package column: path without the gno.land/ prefix, linked to the
		// contract's folder in this repo. Kind emoji after (outside the backtick).
		label := strings.TrimPrefix(c.PkgPath, "gno.land/")
		name := "[`" + label + "`](" + c.Dir + ") " + kindEmoji(c.Kind)
		if c.Draft {
			name += " 🚧"
		}
		if c.Ignored {
			name += " 💤"
		}
		b.WriteString("| " + name + " |")
		for _, n := range m.Networks {
			b.WriteString(" " + publishedCell(n, c) + " |")
		}
		b.WriteString(" " + monorepoLink(c.Upstream, c.UpstreamMatch) + " | " + depBadge(c.Deps) + " |\n")
	}
	b.WriteString("\n_📦 pkg · 🏛️ realm · 🚧 draft · 💤 archived (`ignore = true` in gnomod, skipped by CI; kept for reference, superseded by a later version)._\n")
	b.WriteString("\n_Monorepo `src` vs our copy: 🟰 identical · ≈ identical `.gno` (meta differs) · 〜 identical `.gno` except tests · ✂️ `.gno` drifted._\n")
	if m.StatusCheckedAt != "" {
		b.WriteString("\n_On-chain status last checked: " + m.StatusCheckedAt + " (✅ = /v1, 🗄️ = un-versioned monorepo path)._\n")
	}
	return b.String()
}

// kindEmoji marks a contract as a package or a realm, shown after the package
// name (outside the backtick) in place of a dedicated Kind column.
func kindEmoji(kind string) string {
	if kind == "r" {
		return "🏛️"
	}
	return "📦"
}

// monorepoLink renders a link to the un-versioned package in the gnolang/gno
// monorepo, plus a marker for how our versioned copy compares to it.
func monorepoLink(upstream, match string) string {
	if upstream == "" {
		return "—"
	}
	link := "[src](https://github.com/gnolang/gno/tree/master/examples/" + upstream + ")"
	switch match {
	case "exact":
		return link + " 🟰" // every file identical
	case "gno":
		return link + " ≈" // all .gno identical (gnomod/meta differ)
	case "gno-notest":
		return link + " 〜" // .gno identical except tests
	case "diff":
		return link + " ✂️" // production .gno drifted
	}
	return link
}

func depBadge(deps []string) string {
	if len(deps) == 0 {
		return "—"
	}
	return fmt.Sprintf("%d", len(deps))
}

func publishedBadge(p Pub) string {
	if !p.Uploaded {
		return "—"
	}
	switch p.Which {
	case "monorepo":
		return "🗄️"
	case "both":
		return "✅🗄️"
	default:
		return "✅"
	}
}

// publishedCell renders the per-network status badge, made clickable to the
// package's gnoweb page on that network when it is on chain. A monorepo-only
// hit links the un-versioned path (that is what is actually deployed there).
func publishedCell(n Network, c Contract) string {
	p := c.Published[n.Name]
	badge := publishedBadge(p)
	if !p.Uploaded {
		return badge
	}
	path := gnowebPath(c.PkgPath)
	if p.Which == "monorepo" && c.Upstream != "" {
		path = gnowebPath(c.Upstream)
	}
	return "[" + badge + "](" + webBase(n) + path + ")"
}

// webBase returns the gnoweb base URL for a network, derived from its RPC: the
// "rpc." host prefix is dropped (rpc.gno.land -> gno.land) and the port is
// stripped; a local devnet (127.0.0.1/localhost) maps to gnodev's web port 8888.
func webBase(n Network) string {
	scheme, rest := "https://", n.RPC
	if i := strings.Index(rest, "://"); i >= 0 {
		scheme, rest = rest[:i+3], rest[i+3:]
	}
	if i := strings.IndexByte(rest, '/'); i >= 0 {
		rest = rest[:i]
	}
	host := rest
	if i := strings.LastIndexByte(host, ':'); i >= 0 {
		host = host[:i]
	}
	if host == "127.0.0.1" || host == "localhost" {
		return "http://" + host + ":8888"
	}
	return scheme + strings.TrimPrefix(host, "rpc.")
}

// gnowebPath drops the chain-domain prefix from a pkgpath, keeping the gnoweb
// path: gno.land/p/moul/hello/v1 -> /p/moul/hello/v1.
func gnowebPath(pkgpath string) string {
	if i := strings.IndexByte(pkgpath, '/'); i >= 0 {
		return pkgpath[i:]
	}
	return "/" + pkgpath
}
