package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	tableBegin = "<!-- BEGIN CONTRACTS TABLE (generated by `make readme`; do not edit by hand) -->"
	tableEnd   = "<!-- END CONTRACTS TABLE -->"
)

// cmdReadme regenerates the contracts table in README.md between the marker
// comments, from contracts.json.
func cmdReadme(root string) error {
	m, err := loadManifest(root)
	if err != nil {
		return err
	}
	readmePath := filepath.Join(root, "README.md")
	b, err := os.ReadFile(readmePath)
	if err != nil {
		return err
	}
	content := string(b)
	i := strings.Index(content, tableBegin)
	j := strings.Index(content, tableEnd)
	if i < 0 || j < 0 || j < i {
		return fmt.Errorf("README.md missing the contracts-table markers")
	}
	var out strings.Builder
	out.WriteString(content[:i])
	out.WriteString(tableBegin)
	out.WriteString("\n\n")
	out.WriteString(renderTable(m))
	out.WriteString("\n")
	out.WriteString(content[j:])
	return os.WriteFile(readmePath, []byte(out.String()), 0o644)
}

func renderTable(m *Manifest) string {
	if len(m.Contracts) == 0 {
		return "_No contracts yet._\n"
	}
	var b strings.Builder
	// header
	b.WriteString("| Package | Kind | Description | Deps | Monorepo |")
	for _, n := range m.Networks {
		b.WriteString(" " + n.Name + " |")
	}
	b.WriteString("\n|---|---|---|---|---|")
	for range m.Networks {
		b.WriteString("---|")
	}
	b.WriteString("\n")
	// rows
	for _, c := range m.Contracts {
		desc := c.Description
		if c.Draft {
			desc = "🚧 " + desc
		}
		if c.Ignored {
			desc = "💤 " + desc
		}
		if desc == "" {
			desc = "—"
		}
		kind := "pkg"
		if c.Kind == "r" {
			kind = "realm"
		}
		b.WriteString("| `" + c.PkgPath + "` | " + kind + " | " + desc + " | " + depBadge(c.Deps) + " | " + monorepoLink(c.Upstream) + " |")
		for _, n := range m.Networks {
			b.WriteString(" " + publishedBadge(c.Published[n.Name]) + " |")
		}
		b.WriteString("\n")
	}
	b.WriteString("\n_💤 = archived: `ignore = true` in gnomod, skipped by CI; kept for reference and superseded by a later version._\n")
	if m.StatusCheckedAt != "" {
		b.WriteString("\n_On-chain status last checked: " + m.StatusCheckedAt + " (✅ = /v1, 📦 = un-versioned monorepo path)._\n")
	}
	return b.String()
}

// monorepoLink renders a link to the un-versioned package in the gnolang/gno
// monorepo, for contracts that originated there.
func monorepoLink(upstream string) string {
	if upstream == "" {
		return "—"
	}
	return "[src](https://github.com/gnolang/gno/tree/master/examples/" + upstream + ")"
}

func depBadge(deps []string) string {
	if len(deps) == 0 {
		return "—"
	}
	return fmt.Sprintf("%d", len(deps))
}

func publishedBadge(p Pub) string {
	if !p.Uploaded {
		return "—"
	}
	switch p.Which {
	case "monorepo":
		return "📦"
	case "both":
		return "✅📦"
	default:
		return "✅"
	}
}
