package main

import (
	"strings"
	"testing"
)

const greenReport = `<!-- gnopm-ci-report -->
### gnopm

**287 modules** · 245 in tree · 42 pinned to history

| | check | detail |
|---|---|---|
| ✅ | the lock describes the working tree | every package accounted for |
| ✅ | pinned versions reproduce from history | 42 version(s) rebuilt and hashed |

**What this changes in ` + "`gnomod.lock`" + `**

- added ` + "`gno.land/p/moul/md/v1`" + `

<sub>generated by [gnopm](https://github.com/moul/gnopm)</sub>
`

func TestGnopmFragmentFoldsAGreenReport(t *testing.T) {
	got := gnopmFragment(greenReport)
	// The gnopm attribution is kept on purpose: inside a section this comment
	// owns, saying which tool wrote the table is the only thing that does.
	for _, want := range []string{"<details>", "every check green", "the lock describes the working tree", "generated by [gnopm]"} {
		if !strings.Contains(got, want) {
			t.Fatalf("expected %q in:\n%s", want, got)
		}
	}
	// The marker is gnopm's handle on its own sticky comment, and the lock
	// changes are already rendered by lockReport from the same file.
	for _, unwanted := range []string{"gnopm-ci-report", "What this changes", "gno.land/p/moul/md/v1"} {
		if strings.Contains(got, unwanted) {
			t.Fatalf("did not expect %q in:\n%s", unwanted, got)
		}
	}
}

func TestGnopmFragmentLeavesAFailureOpen(t *testing.T) {
	red := strings.Replace(greenReport, "| ✅ | the lock describes", "| ❌ | the lock describes", 1)
	got := gnopmFragment(red)
	if strings.Contains(got, "<details>") {
		t.Fatalf("a failing report must not be folded away:\n%s", got)
	}
	if !strings.Contains(got, "❌") {
		t.Fatalf("expected the failure mark in:\n%s", got)
	}
}

func TestGnopmFragmentIsEmptyWithoutAReport(t *testing.T) {
	if got := gnopmFragment("   \n "); got != "" {
		t.Fatalf("expected nothing, got %q", got)
	}
	if got := readGnopmReport(""); got != "" {
		t.Fatalf("expected nothing, got %q", got)
	}
	if got := readGnopmReport("/nonexistent/gnopm-ci.md"); got != "" {
		t.Fatalf("a missing report must not break the comment, got %q", got)
	}
}
