#!/usr/bin/env python3
"""Generate one AMM pair instance realm, the gno equivalent of a factory call.

Ethereum spawns a pair from inside a contract (`factory.createPair`). gno has no
on-chain deploy at all: `vm/add_package` is permanently denied to realm code, so
creating an instance is an `addpkg` transaction signed by a human. This script is
that factory, and it runs on your machine.

What it writes is deliberately boring: two constants, an init that builds the
pair and announces it to the registry, and one-line re-exports forwarding `cur`
into gno.land/p/moul/x/pair/v0. Two generated instances differ only in the two
constants and the package name, which is what makes verifying an unknown
instance a two-line diff (nothing on chain can attest an instance's code, see
the registry's package doc).

Usage:

    tools/pairgen.py <keyA> <keyB> [-o DIR] [--namespace NS]

    # a pair for two grc20reg-registered tokens, under your own address
    tools/pairgen.py gno.land/r/nt/foo20/v0.FOO gno.land/r/nt/bar20/v0.BAR \\
        --namespace g1jg8mtutu9khhfwc4nxmuhcpftf0pajdhfvsqf5/pair --key moul

It prints the gnokey command to deploy what it wrote. It never broadcasts.
"""
import argparse
import pathlib
import re
import sys

TEMPLATE = '''// Realm {pkg} is ONE AMM pair, {symA}/{symB}, and nothing else.
//
// Generated by tools/pairgen.py. Every instance is byte-identical to this file
// except for the package name and the two constants below, so diffing an
// unknown instance against a freshly generated one is the whole verification
// story: gno cannot attest a package's code on chain.
//
// State and funds belong to THIS realm. A bug in one instance cannot touch
// another, and its creator paid its storage deposit.
//
// Pattern: see the README of gno.land/p/moul/x/pair/v0.
package {pkg}

import (
\t"gno.land/p/moul/x/pair/v0"
\t"gno.land/r/moul/x/pairreg/v0"
\t"gno.land/r/nt/grc20reg/v0"
)

// The only two lines that differ between two instances.
const (
\tkeyA = "{keyA}"
\tkeyB = "{keyB}"
)

var p *pair.Pair

func init(cur realm) {{
\tp = pair.New(keyA, keyB, grc20reg.MustGet(keyA), grc20reg.MustGet(keyB))
\tpairreg.Register(cross(cur), p)
}}

func AddLiquidity(cur realm, maxA, maxB int64) int64 {{ return p.AddLiquidity(0, cur, maxA, maxB) }}

func RemoveLiquidity(cur realm, shares int64) (int64, int64) {{
\treturn p.RemoveLiquidity(0, cur, shares)
}}

func Swap(cur realm, keyIn string, amountIn, minOut int64) int64 {{
\treturn p.Swap(0, cur, keyIn, amountIn, minOut)
}}

func Quote(keyIn string, amountIn int64) int64 {{ return p.Quote(keyIn, amountIn) }}
func Reserves() (int64, int64)                 {{ return p.Reserves() }}
func SharesOf(owner address) int64             {{ return p.SharesOf(owner) }}
func TotalShares() int64                       {{ return p.TotalShares() }}
func Keys() (string, string)                   {{ return p.Keys() }}
func Render(path string) string                {{ return p.Render(path) }}
'''

GNOMOD = 'module = "{path}"\ngno = "0.9"\n'


def symbol_of(key: str) -> str:
    """The grc20reg key is `<realm path>.<SYMBOL>`; take the symbol."""
    tail = key.rsplit("/", 1)[-1]
    if "." not in tail:
        sys.exit(f"pairgen: {key} is not a grc20reg key (expected <path>.<SYMBOL>)")
    return tail.rsplit(".", 1)[-1]


def pkg_name(symA: str, symB: str) -> str:
    """A gno package name is an identifier: no hyphens, no leading digit."""
    name = re.sub(r"[^a-z0-9]", "", (symA + symB).lower())
    if not name or name[0].isdigit():
        name = "pair" + name
    return name


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("keyA", help="grc20reg key of the first token, <realm path>.<SYMBOL>")
    ap.add_argument("keyB", help="grc20reg key of the second token")
    ap.add_argument("-o", "--out", default=".", help="directory to write the instance into")
    ap.add_argument("--namespace", default="<your g1 address or registered name>",
                    help="path prefix under gno.land/r/ the instance is deployed at")
    ap.add_argument("--key", default="moul", help="gnokey keybase entry to sign the deploy with")
    args = ap.parse_args()

    keyA, keyB = args.keyA, args.keyB
    if keyA == keyB:
        sys.exit("pairgen: a pair needs two different tokens")
    # Canonicalise exactly as pair.New does, so the generated file and the
    # on-chain pair agree on which side is A.
    if keyA > keyB:
        keyA, keyB = keyB, keyA
    symA, symB = symbol_of(keyA), symbol_of(keyB)
    pkg = pkg_name(symA, symB)

    path = f"gno.land/r/{args.namespace}/{pkg}/v0"
    dest = pathlib.Path(args.out) / pkg / "v0"
    dest.mkdir(parents=True, exist_ok=True)
    (dest / f"{pkg}.gno").write_text(
        TEMPLATE.format(pkg=pkg, symA=symA, symB=symB, keyA=keyA, keyB=keyB))
    (dest / "gnomod.toml").write_text(GNOMOD.format(path=path))

    print(f"wrote {dest}/{pkg}.gno")
    print(f"      {dest}/gnomod.toml")
    print()
    print("deploy it with:")
    print()
    print(f"  gnokey maketx addpkg -pkgpath {path} \\")
    print(f"    -pkgdir {dest} -gas-fee 1000000ugnot -gas-wanted 20000000 \\")
    print(f"    -broadcast -chainid gnoland-1 -remote https://rpc.gno.land:443 {args.key}")
    print()
    print("Deploying also registers it: the init calls pairreg.Register, so one")
    print("transaction creates the pair and lists it on /r/moul/x/pairreg/v0.")


if __name__ == "__main__":
    main()
